/**
 * Auto-generated React Query hooks for Frontend API v2
 * Generated from: /Users/sboulos/Desktop/ai_projects/xano-v2-admin/lib/frontend-api-v2-openapi.json
 * Base URL: https://x2nu-xcjc-vhax.agentdashboards.xano.io/api:pe1wjL5I
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Run 'npm run hooks:gen' to regenerate
 */

import { useQuery, useMutation, useQueryClient, QueryClient } from '@tanstack/react-query'
import type { UseQueryOptions, UseMutationOptions } from '@tanstack/react-query'
import { api } from './client'
import type { paths } from './generated-types'


/**
 * Endpoint created via MCP - untitled-endpoint
 * POST /admin/resync-user
 */
export function useCreateAdminResyncUser(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/admin/resync-user', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['admin-resync-user'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - admin
 * GET /admin
 */
export function useAdmin(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['admin', params],
    queryFn: () => api.get('/admin', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - backfill-agent-team-id-v2
 * POST /backfill-agent-team-id-v2
 */
export function useCreateBackfillAgentTeamIdV2(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/backfill-agent-team-id-v2', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['backfill-agent-team-id-v2'] })
    },
    ...options,
  })
}

/**
 * Network Activity Chart - Server-side transform
 * GET /chart/network-activity
 */
export function useChartNetworkActivity(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['chart-network-activity', params],
    queryFn: () => api.get('/chart/network-activity', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - untitled-endpoint
 * GET /chart/revenue-by-agent
 */
export function useChartRevenueByAgent(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['chart-revenue-by-agent', params],
    queryFn: () => api.get('/chart/revenue-by-agent', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - untitled-endpoint
 * GET /chart/revenue-trends
 */
export function useChartRevenueTrends(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['chart-revenue-trends', params],
    queryFn: () => api.get('/chart/revenue-trends', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - untitled-endpoint
 * GET /chart/transactions-status
 */
export function useChartTransactionsStatus(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['chart-transactions-status', params],
    queryFn: () => api.get('/chart/transactions-status', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - chart_catalog/{chart_catalog_id}
 * PATCH /chart_catalog/{chart_catalog_id}
 */
export function useChart_catalog(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.patch('/chart_catalog/{chart_catalog_id}', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['chart_catalog-{chart_catalog_id}'] })
    },
    ...options,
  })
}

/**
 * Get all available charts from catalog
 * GET /chart_catalog
 */
export function useChart_catalogGet(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['chart_catalog', params],
    queryFn: () => api.get('/chart_catalog', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - contact_log
 * GET /contact_log
 */
export function useContact_log(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['contact_log', params],
    queryFn: () => api.get('/contact_log', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - contact_log
 * POST /contact_log
 */
export function useCreateContact_log(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/contact_log', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['contact_log'] })
    },
    ...options,
  })
}

/**
 * Contributions endpoint - returns contributions with contributor names for the authenticated user
 * GET /contributions
 */
export function useContributions(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['contributions', params],
    queryFn: () => api.get('/contributions', { params }),
    ...options,
  })
}

/**
 * Endpoint: csv/configure_mapping/list - List all CSV mappings for user
 * GET /csv/configure_mapping/list
 */
export function useCsvConfigure_mappingList(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['csv-configure_mapping-list', params],
    queryFn: () => api.get('/csv/configure_mapping/list', { params }),
    ...options,
  })
}

/**
 * Endpoint: csv/configure_mapping - Save CSV mapping configuration
 * POST /csv/configure_mapping
 */
export function useCreateCsvConfigure_mapping(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/csv/configure_mapping', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['csv-configure_mapping'] })
    },
    ...options,
  })
}

/**
 * Endpoint: csv/process_batch - Process CSV batch import
 * POST /csv/process_batch
 */
export function useCreateCsvProcess_batch(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/csv/process_batch', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['csv-process_batch'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - csv/upload
 * GET /csv/upload
 */
export function useCsvUpload(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['csv-upload', params],
    queryFn: () => api.get('/csv/upload', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - csv/validate
 * POST /csv/validate
 */
export function useCreateCsvValidate(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/csv/validate', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['csv-validate'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - dashboard/roster_data
 * GET /dashboard/roster_data
 */
export function useDashboardRoster_data(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['dashboard-roster_data', params],
    queryFn: () => api.get('/dashboard/roster_data', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - dashboard_sections
 * GET /dashboard_sections
 */
export function useDashboard_sections(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['dashboard_sections', params],
    queryFn: () => api.get('/dashboard_sections', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - dashboard_sections
 * POST /dashboard_sections
 */
export function useCreateDashboard_sections(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/dashboard_sections', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['dashboard_sections'] })
    },
    ...options,
  })
}

/**
 * Update a favorite chart configuration
 * PATCH /favorites_id
 */
export function useFavorites_id(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.patch('/favorites_id', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['favorites_id'] })
    },
    ...options,
  })
}

/**
 * Get user's favorites
 * GET /favorites
 */
export function useFavorites(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['favorites', params],
    queryFn: () => api.get('/favorites', { params }),
    ...options,
  })
}

/**
 * Add a favorite chart to user dashboard
 * POST /favorites
 */
export function useCreateFavorites(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/favorites', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['favorites'] })
    },
    ...options,
  })
}

/**
 * FUB Appointments - List all appointments
 * GET /fub/appointments
 */
export function useFubAppointments(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['fub-appointments', params],
    queryFn: () => api.get('/fub/appointments', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - fub/bulk_add_people
 * POST /fub/bulk_add_people
 */
export function useCreateFubBulk_add_people(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/fub/bulk_add_people', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['fub-bulk_add_people'] })
    },
    ...options,
  })
}

/**
 * FUB Events - List all events
 * GET /fub/events
 */
export function useFubEvents(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['fub-events', params],
    queryFn: () => api.get('/fub/events', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - fub/lambda_failed_records
 * POST /fub/lambda_failed_records
 */
export function useCreateFubLambda_failed_records(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/fub/lambda_failed_records', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['fub-lambda_failed_records'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - fub/lambda_worker_logs/id
 * PATCH /fub/lambda_worker_logs/id
 */
export function useFubLambda_worker_logsId(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.patch('/fub/lambda_worker_logs/id', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['fub-lambda_worker_logs-id'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - fub/lambda_worker_logs
 * POST /fub/lambda_worker_logs
 */
export function useCreateFubLambda_worker_logs(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/fub/lambda_worker_logs', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['fub-lambda_worker_logs'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - fub/people
 * GET /fub/people
 */
export function useFubPeople(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['fub-people', params],
    queryFn: () => api.get('/fub/people', { params }),
    ...options,
  })
}

/**
 * FUB Text Messages - List all text messages  
 * GET /fub/text_messages
 */
export function useFubText_messages(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['fub-text_messages', params],
    queryFn: () => api.get('/fub/text_messages', { params }),
    ...options,
  })
}

/**
 * GET goals endpoint - fixed table name
 * GET /goals
 */
export function useGoals(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['goals', params],
    queryFn: () => api.get('/goals', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - /has_transactions
 * GET /has_transactions
 */
export function useHas_transactions(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['has_transactions', params],
    queryFn: () => api.get('/has_transactions', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - importer/create_token
 * GET /importer/create_token
 */
export function useImporterCreate_token(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['importer-create_token', params],
    queryFn: () => api.get('/importer/create_token', { params }),
    ...options,
  })
}

/**
 * Complete FUB OAuth Flow - Exchange code, save tokens, create job records
 * POST /integrations/code
 */
export function useCreateIntegrationsCode(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/integrations/code', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['integrations-code'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - integrations/connect-rezen
 * POST /integrations/connect-rezen
 */
export function useCreateIntegrationsConnectRezen(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/integrations/connect-rezen', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['integrations-connect-rezen'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - integrations/disconnect
 * POST /integrations/disconnect
 */
export function useCreateIntegrationsDisconnect(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/integrations/disconnect', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['integrations-disconnect'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - integrations/url
 * GET /integrations/url
 */
export function useIntegrationsUrl(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['integrations-url', params],
    queryFn: () => api.get('/integrations/url', { params }),
    ...options,
  })
}

/**
 * GET kpi_goals/list endpoint - team_id optional
 * GET /kpi_goals/list
 */
export function useKpi_goalsList(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['kpi_goals-list', params],
    queryFn: () => api.get('/kpi_goals/list', { params }),
    ...options,
  })
}

/**
 * POST kpi_goals/save endpoint - fixed table name
 * POST /kpi_goals/save
 */
export function useCreateKpi_goalsSave(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/kpi_goals/save', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['kpi_goals-save'] })
    },
    ...options,
  })
}

/**
 * Alias endpoint for kpi_goals_list (underscore naming)
 * GET /kpi_goals_list
 */
export function useKpi_goals_list(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['kpi_goals_list', params],
    queryFn: () => api.get('/kpi_goals_list', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - lambda/job_checkpoint
 * POST /lambda/job_checkpoint
 */
export function useCreateLambdaJob_checkpoint(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/lambda/job_checkpoint', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['lambda-job_checkpoint'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - leaderboard/computed
 * GET /leaderboard/computed
 */
export function useLeaderboardComputed(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['leaderboard-computed', params],
    queryFn: () => api.get('/leaderboard/computed', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - leaderboard/show_stats
 * POST /leaderboard/show_stats
 */
export function useCreateLeaderboardShow_stats(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/leaderboard/show_stats', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['leaderboard-show_stats'] })
    },
    ...options,
  })
}

/**
 * Get transactions for leaderboard view
Works with or without auth - uses input team_id or falls back to auth.team_id
Returns dates as ISO strings for frontend compatibility
 * GET /leaderboard/transactions
 */
export function useLeaderboardTransactions(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['leaderboard-transactions', params],
    queryFn: () => api.get('/leaderboard/transactions', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - leads/all
 * GET /leads/all
 */
export function useLeadsAll(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['leads-all', params],
    queryFn: () => api.get('/leads/all', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - leads/fub/appointments/aggregates
 * GET /leads/fub/appointments/aggregates
 */
export function useLeadsFubAppointmentsAggregates(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['leads-fub-appointments-aggregates', params],
    queryFn: () => api.get('/leads/fub/appointments/aggregates', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - leads/fub/calls/aggregates
 * GET /leads/fub/calls/aggregates
 */
export function useLeadsFubCallsAggregates(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['leads-fub-calls-aggregates', params],
    queryFn: () => api.get('/leads/fub/calls/aggregates', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - leads/fub/calls
 * GET /leads/fub/calls
 */
export function useLeadsFubCalls(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['leads-fub-calls', params],
    queryFn: () => api.get('/leads/fub/calls', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - leads/fub/deals/aggregates
 * GET /leads/fub/deals/aggregates
 */
export function useLeadsFubDealsAggregates(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['leads-fub-deals-aggregates', params],
    queryFn: () => api.get('/leads/fub/deals/aggregates', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - leads/fub/deals
 * GET /leads/fub/deals
 */
export function useLeadsFubDeals(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['leads-fub-deals', params],
    queryFn: () => api.get('/leads/fub/deals', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - leads/fub/events/aggregates
 * GET /leads/fub/events/aggregates
 */
export function useLeadsFubEventsAggregates(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['leads-fub-events-aggregates', params],
    queryFn: () => api.get('/leads/fub/events/aggregates', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - leads/fub/events
 * GET /leads/fub/events
 */
export function useLeadsFubEvents(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['leads-fub-events', params],
    queryFn: () => api.get('/leads/fub/events', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - leads/fub/people/aggregates
 * GET /leads/fub/people/aggregates
 */
export function useLeadsFubPeopleAggregates(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['leads-fub-people-aggregates', params],
    queryFn: () => api.get('/leads/fub/people/aggregates', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - leads/fub/people
 * GET /leads/fub/people
 */
export function useLeadsFubPeople(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['leads-fub-people', params],
    queryFn: () => api.get('/leads/fub/people', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - leads/fub/text_messages/aggregates
 * GET /leads/fub/text_messages/aggregates
 */
export function useLeadsFubText_messagesAggregates(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['leads-fub-text_messages-aggregates', params],
    queryFn: () => api.get('/leads/fub/text_messages/aggregates', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - /links
 * GET /links
 */
export function useLinks(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['links', params],
    queryFn: () => api.get('/links', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - /links
 * POST /links
 */
export function useCreateLinks(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/links', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['links'] })
    },
    ...options,
  })
}

/**
 * Endpoint: listings/all - Returns all listings with address and agent data
FIXED: Returns address fields BOTH nested (_address) and flat (street, city, etc.)
 * GET /listings/all
 */
export function useListingsAll(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['listings-all', params],
    queryFn: () => api.get('/listings/all', { params }),
    ...options,
  })
}

/**
 * v2 normalized: Get listing counts by stage
 * GET /listings/count
 */
export function useListingsCount(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['listings-count', params],
    queryFn: () => api.get('/listings/count', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - login/slack_error
 * GET /login/slack_error
 */
export function useLoginSlack_error(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['login-slack_error', params],
    queryFn: () => api.get('/login/slack_error', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - login/team_seat-multi
 * GET /login/team_seat-multi
 */
export function useLoginTeam_seatMulti(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['login-team_seat-multi', params],
    queryFn: () => api.get('/login/team_seat-multi', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - login/team_seat-public
 * GET /login/team_seat-public
 */
export function useLoginTeam_seatPublic(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['login-team_seat-public', params],
    queryFn: () => api.get('/login/team_seat-public', { params }),
    ...options,
  })
}

/**
 * Get all network members for the authenticated user
 * GET /network/all
 */
export function useNetworkAll(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['network-all', params],
    queryFn: () => api.get('/network/all', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - network/counts
 * GET /network/counts
 */
export function useNetworkCounts(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['network-counts', params],
    queryFn: () => api.get('/network/counts', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - network/favorite
 * POST /network/favorite
 */
export function useCreateNetworkFavorite(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/network/favorite', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['network-favorite'] })
    },
    ...options,
  })
}

/**
 * Update contact frequency for network member
 * POST /network/frequency
 */
export function useCreateNetworkFrequency(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/network/frequency', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['network-frequency'] })
    },
    ...options,
  })
}

/**
 * Update last contacted date for network member
 * POST /network/last_contacted_date
 */
export function useCreateNetworkLast_contacted_date(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/network/last_contacted_date', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['network-last_contacted_date'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - network/pipeline/card
 * DELETE /network/pipeline/card
 */
export function useDeleteNetworkPipelineCard(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.delete('/network/pipeline/card', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['network-pipeline-card'] })
    },
    ...options,
  })
}

/**
 * Edit a pipeline prospect card - all fields optional except id
 * POST /network/pipeline/edit_card
 */
export function useCreateNetworkPipelineEdit_card(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/network/pipeline/edit_card', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['network-pipeline-edit_card'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - network/pipeline/new_card
 * POST /network/pipeline/new_card
 */
export function useCreateNetworkPipelineNew_card(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/network/pipeline/new_card', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['network-pipeline-new_card'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - network/pipeline/stage_update
 * POST /network/pipeline/stage_update
 */
export function useCreateNetworkPipelineStage_update(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/network/pipeline/stage_update', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['network-pipeline-stage_update'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - network/pipeline/stage
 * DELETE /network/pipeline/stage
 */
export function useDeleteNetworkPipelineStage(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.delete('/network/pipeline/stage', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['network-pipeline-stage'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - network/pipeline/stage
 * POST /network/pipeline/stage
 */
export function useCreateNetworkPipelineStage(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/network/pipeline/stage', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['network-pipeline-stage'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - network/pipeline/status_changed
 * POST /network/pipeline/status_changed
 */
export function useCreateNetworkPipelineStatus_changed(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/network/pipeline/status_changed', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['network-pipeline-status_changed'] })
    },
    ...options,
  })
}

/**
 * Network pipeline - get stages and prospects
 * GET /network/pipeline
 */
export function useNetworkPipeline(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['network-pipeline', params],
    queryFn: () => api.get('/network/pipeline', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - network/unfavorite
 * POST /network/unfavorite
 */
export function useCreateNetworkUnfavorite(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/network/unfavorite', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['network-unfavorite'] })
    },
    ...options,
  })
}

/**
 * Add a message to a NORA conversation
 * POST /nora/conversations/{conversation_id}/messages
 */
export function useCreateNoraConversationsMessages(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/nora/conversations/{conversation_id}/messages', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['nora-conversations-{conversation_id}-messages'] })
    },
    ...options,
  })
}

/**
 * Delete a NORA conversation
 * DELETE /nora/conversations/{conversation_id}
 */
export function useDeleteNoraConversations(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.delete('/nora/conversations/{conversation_id}', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['nora-conversations-{conversation_id}'] })
    },
    ...options,
  })
}

/**
 * Get a specific NORA conversation
 * GET /nora/conversations/{conversation_id}
 */
export function useNoraConversations(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['nora-conversations-{conversation_id}', params],
    queryFn: () => api.get('/nora/conversations/{conversation_id}', { params }),
    ...options,
  })
}

/**
 * Get all NORA conversations for the authenticated user
 * GET /nora/conversations
 */
export function useNoraConversationsGet(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['nora-conversations', params],
    queryFn: () => api.get('/nora/conversations', { params }),
    ...options,
  })
}

/**
 * Create a new NORA conversation
 * POST /nora/conversations
 */
export function useCreateNoraConversations(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/nora/conversations', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['nora-conversations'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - untitled-endpoint
 * POST /nora/generate
 */
export function useCreateNoraGenerate(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/nora/generate', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['nora-generate'] })
    },
    ...options,
  })
}

/**
 * Fixed: nora/notifications_summary - Use authenticated user
 * GET /nora/notifications_summary
 */
export function useNoraNotifications_summary(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['nora-notifications_summary', params],
    queryFn: () => api.get('/nora/notifications_summary', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - onboarding/default_team
 * GET /onboarding/default_team
 */
export function useOnboardingDefault_team(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['onboarding-default_team', params],
    queryFn: () => api.get('/onboarding/default_team', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/configuration
 * GET /page_builder/configuration
 */
export function usePage_builderConfiguration(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['page_builder-configuration', params],
    queryFn: () => api.get('/page_builder/configuration', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/config
 * GET /page_builder/config
 */
export function usePage_builderConfig(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['page_builder-config', params],
    queryFn: () => api.get('/page_builder/config', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/filter_options/create
 * POST /page_builder/filter_options/create
 */
export function useCreatePage_builderFilter_optionsCreate(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/page_builder/filter_options/create', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-filter_options-create'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/filter_options/delete
 * DELETE /page_builder/filter_options/delete
 */
export function useDeletePage_builderFilter_optionsDelete(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.delete('/page_builder/filter_options/delete', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-filter_options-delete'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/filter_options/update
 * PATCH /page_builder/filter_options/update
 */
export function usePage_builderFilter_optionsUpdate(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.patch('/page_builder/filter_options/update', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-filter_options-update'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/filter_options
 * GET /page_builder/filter_options
 */
export function usePage_builderFilter_options(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['page_builder-filter_options', params],
    queryFn: () => api.get('/page_builder/filter_options', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/filters/by-slug
 * GET /page_builder/filters/by-slug
 */
export function usePage_builderFiltersBySlug(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['page_builder-filters-by-slug', params],
    queryFn: () => api.get('/page_builder/filters/by-slug', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/filters/delete
 * DELETE /page_builder/filters/delete
 */
export function useDeletePage_builderFiltersDelete(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.delete('/page_builder/filters/delete', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-filters-delete'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/filters/reorder
 * POST /page_builder/filters/reorder
 */
export function useCreatePage_builderFiltersReorder(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/page_builder/filters/reorder', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-filters-reorder'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/filters/update
 * PATCH /page_builder/filters/update
 */
export function usePage_builderFiltersUpdate(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.patch('/page_builder/filters/update', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-filters-update'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/filters
 * GET /page_builder/filters
 */
export function usePage_builderFilters(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['page_builder-filters', params],
    queryFn: () => api.get('/page_builder/filters', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/filters
 * POST /page_builder/filters
 */
export function useCreatePage_builderFilters(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/page_builder/filters', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-filters'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/pages/by-slug
 * GET /page_builder/pages/by-slug
 */
export function usePage_builderPagesBySlug(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['page_builder-pages-by-slug', params],
    queryFn: () => api.get('/page_builder/pages/by-slug', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/pages/delete
 * DELETE /page_builder/pages/delete
 */
export function useDeletePage_builderPagesDelete(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.delete('/page_builder/pages/delete', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-pages-delete'] })
    },
    ...options,
  })
}

/**
 * Update page - all fields optional except id
 * PATCH /page_builder/pages/update
 */
export function usePage_builderPagesUpdate(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.patch('/page_builder/pages/update', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-pages-update'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/pages
 * GET /page_builder/pages
 */
export function usePage_builderPages(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['page_builder-pages', params],
    queryFn: () => api.get('/page_builder/pages', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/pages
 * POST /page_builder/pages
 */
export function useCreatePage_builderPages(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/page_builder/pages', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-pages'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/sections/delete
 * DELETE /page_builder/sections/delete
 */
export function useDeletePage_builderSectionsDelete(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.delete('/page_builder/sections/delete', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-sections-delete'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/sections/reorder
 * POST /page_builder/sections/reorder
 */
export function useCreatePage_builderSectionsReorder(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/page_builder/sections/reorder', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-sections-reorder'] })
    },
    ...options,
  })
}

/**
 * Update section - all fields optional except id
 * PATCH /page_builder/sections/update
 */
export function usePage_builderSectionsUpdate(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.patch('/page_builder/sections/update', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-sections-update'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/sections
 * GET /page_builder/sections
 */
export function usePage_builderSections(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['page_builder-sections', params],
    queryFn: () => api.get('/page_builder/sections', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/sections
 * POST /page_builder/sections
 */
export function useCreatePage_builderSections(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/page_builder/sections', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-sections'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/tabs/delete
 * DELETE /page_builder/tabs/delete
 */
export function useDeletePage_builderTabsDelete(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.delete('/page_builder/tabs/delete', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-tabs-delete'] })
    },
    ...options,
  })
}

/**
 * Update tab - all fields optional except id
 * PATCH /page_builder/tabs/update
 */
export function usePage_builderTabsUpdate(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.patch('/page_builder/tabs/update', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-tabs-update'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/tabs
 * GET /page_builder/tabs
 */
export function usePage_builderTabs(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['page_builder-tabs', params],
    queryFn: () => api.get('/page_builder/tabs', { params }),
    ...options,
  })
}

/**
 * Create tab - icon is optional
 * POST /page_builder/tabs
 */
export function useCreatePage_builderTabs(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/page_builder/tabs', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-tabs'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/user_filter_preferences/delete
 * DELETE /page_builder/user_filter_preferences/delete
 */
export function useDeletePage_builderUser_filter_preferencesDelete(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.delete('/page_builder/user_filter_preferences/delete', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-user_filter_preferences-delete'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/user_filter_preferences/save
 * POST /page_builder/user_filter_preferences/save
 */
export function useCreatePage_builderUser_filter_preferencesSave(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/page_builder/user_filter_preferences/save', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-user_filter_preferences-save'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/user_filter_preferences
 * GET /page_builder/user_filter_preferences
 */
export function usePage_builderUser_filter_preferences(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['page_builder-user_filter_preferences', params],
    queryFn: () => api.get('/page_builder/user_filter_preferences', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/widget_viewport_layouts/save
 * POST /page_builder/widget_viewport_layouts/save
 */
export function useCreatePage_builderWidget_viewport_layoutsSave(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/page_builder/widget_viewport_layouts/save', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-widget_viewport_layouts-save'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/widget_viewport_layouts
 * GET /page_builder/widget_viewport_layouts
 */
export function usePage_builderWidget_viewport_layouts(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['page_builder-widget_viewport_layouts', params],
    queryFn: () => api.get('/page_builder/widget_viewport_layouts', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/widgets/delete
 * DELETE /page_builder/widgets/delete
 */
export function useDeletePage_builderWidgetsDelete(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.delete('/page_builder/widgets/delete', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-widgets-delete'] })
    },
    ...options,
  })
}

/**
 * Update widget - all fields optional except id
 * PATCH /page_builder/widgets/update
 */
export function usePage_builderWidgetsUpdate(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.patch('/page_builder/widgets/update', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-widgets-update'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/widgets
 * GET /page_builder/widgets
 */
export function usePage_builderWidgets(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['page_builder-widgets', params],
    queryFn: () => api.get('/page_builder/widgets', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - page_builder/widgets
 * POST /page_builder/widgets
 */
export function useCreatePage_builderWidgets(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/page_builder/widgets', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['page_builder-widgets'] })
    },
    ...options,
  })
}

/**
 * Revenue endpoint - filters out null dates and normalizes type field
UPDATED 2025-12-22: Added type normalization (Aggregate -> Compensation) for frontend compatibility
 * GET /revenue/all
 */
export function useRevenueAll(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['revenue-all', params],
    queryFn: () => api.get('/revenue/all', { params }),
    ...options,
  })
}

/**
 * RevShare Totals - Returns comprehensive revshare data for the authenticated user
 * GET /revshare_totals
 */
export function useRevshare_totals(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['revshare_totals', params],
    queryFn: () => api.get('/revshare_totals', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - staff_management/admin
 * GET /staff_management/admin
 */
export function useStaff_managementAdmin(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['staff_management-admin', params],
    queryFn: () => api.get('/staff_management/admin', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - staff_management/agents_with_seats
 * GET /staff_management/agents_with_seats
 */
export function useStaff_managementAgents_with_seats(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['staff_management-agents_with_seats', params],
    queryFn: () => api.get('/staff_management/agents_with_seats', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - staff_management/all
 * GET /staff_management/all
 */
export function useStaff_managementAll(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['staff_management-all', params],
    queryFn: () => api.get('/staff_management/all', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - staff_management/delete
 * POST /staff_management/delete
 */
export function useCreateStaff_managementDelete(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/staff_management/delete', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['staff_management-delete'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - staff_management/invite
 * POST /staff_management/invite
 */
export function useCreateStaff_managementInvite(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/staff_management/invite', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['staff_management-invite'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - staff_management/update
 * POST /staff_management/update
 */
export function useCreateStaff_managementUpdate(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/staff_management/update', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['staff_management-update'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - stripe/checkout
 * POST /stripe/checkout
 */
export function useCreateStripeCheckout(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/stripe/checkout', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['stripe-checkout'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - stripe/pricing
 * GET /stripe/pricing
 */
export function useStripePricing(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['stripe-pricing', params],
    queryFn: () => api.get('/stripe/pricing', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - stripe/user_subscription
 * GET /stripe/user_subscription
 */
export function useStripeUser_subscription(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['stripe-user_subscription', params],
    queryFn: () => api.get('/stripe/user_subscription', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - team/remove_logo
 * POST /team/remove_logo
 */
export function useCreateTeamRemove_logo(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/team/remove_logo', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['team-remove_logo'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - team/update_logo
 * POST /team/update_logo
 */
export function useCreateTeamUpdate_logo(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/team/update_logo', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['team-update_logo'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_management/agent_by_id
 * GET /team_management/agent_by_id
 */
export function useTeam_managementAgent_by_id(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['team_management-agent_by_id', params],
    queryFn: () => api.get('/team_management/agent_by_id', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_management/agents_all
 * GET /team_management/agents_all
 */
export function useTeam_managementAgents_all(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['team_management-agents_all', params],
    queryFn: () => api.get('/team_management/agents_all', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_management/count
TEMPORARY: Using legacy 'user' table until data migration to normalized tables completes
 * GET /team_management/count
 */
export function useTeam_managementCount(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['team_management-count', params],
    queryFn: () => api.get('/team_management/count', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_management/details
 * POST /team_management/details
 */
export function useCreateTeam_managementDetails(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/team_management/details', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['team_management-details'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_management/directors_all
 * GET /team_management/directors_all
 */
export function useTeam_managementDirectors_all(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['team_management-directors_all', params],
    queryFn: () => api.get('/team_management/directors_all', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_management/directors
Note: Returns director records with agent_id. Search by name requires frontend filtering with agent data.
 * GET /team_management/directors
 */
export function useTeam_managementDirectors(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['team_management-directors', params],
    queryFn: () => api.get('/team_management/directors', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_management/hide
 * POST /team_management/hide
 */
export function useCreateTeam_managementHide(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/team_management/hide', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['team_management-hide'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_management/leaders_all
 * GET /team_management/leaders_all
 */
export function useTeam_managementLeaders_all(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['team_management-leaders_all', params],
    queryFn: () => api.get('/team_management/leaders_all', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_management/leaders
 * GET /team_management/leaders
 */
export function useTeam_managementLeaders(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['team_management-leaders', params],
    queryFn: () => api.get('/team_management/leaders', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_management/members
 * GET /team_management/members
 */
export function useTeam_managementMembers(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['team_management-members', params],
    queryFn: () => api.get('/team_management/members', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_management/mentors_all
 * GET /team_management/mentors_all
 */
export function useTeam_managementMentors_all(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['team_management-mentors_all', params],
    queryFn: () => api.get('/team_management/mentors_all', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_management/paid_participants
 * GET /team_management/paid_participants
 */
export function useTeam_managementPaid_participants(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['team_management-paid_participants', params],
    queryFn: () => api.get('/team_management/paid_participants', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_management/roster/count
 * GET /team_management/roster/count
 */
export function useTeam_managementRosterCount(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['team_management-roster-count', params],
    queryFn: () => api.get('/team_management/roster/count', { params }),
    ...options,
  })
}

/**
 * Team roster - queries team_members then enriches with agent data
UPDATED 2025-12-22: Added transaction address fallback when agent has no home_address_id
 * GET /team_management/roster
 */
export function useTeam_managementRoster(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['team_management-roster', params],
    queryFn: () => api.get('/team_management/roster', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_management/seats
 * GET /team_management/seats
 */
export function useTeam_managementSeats(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['team_management-seats', params],
    queryFn: () => api.get('/team_management/seats', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_management/seat
 * POST /team_management/seat
 */
export function useCreateTeam_managementSeat(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/team_management/seat', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['team_management-seat'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_management/settings
 * POST /team_management/settings
 */
export function useCreateTeam_managementSettings(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/team_management/settings', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['team_management-settings'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_roster/update_coordinates
 * PATCH /team_roster/update_coordinates
 */
export function useTeam_rosterUpdate_coordinates(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.patch('/team_roster/update_coordinates', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['team_roster-update_coordinates'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - team_roster/update
 * POST /team_roster/update
 */
export function useCreateTeam_rosterUpdate(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/team_roster/update', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['team_roster-update'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - team
 * GET /team
 */
export function useTeam(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['team', params],
    queryFn: () => api.get('/team', { params }),
    ...options,
  })
}

/**
 * Test endpoint - using db.direct_query for true SQL aggregation
 * GET /test/aggregate-syntax
 */
export function useTestAggregateSyntax(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['test-aggregate-syntax', params],
    queryFn: () => api.get('/test/aggregate-syntax', { params }),
    ...options,
  })
}

/**
 * OPTIMIZED: Raw SQL for maximum performance - no foreach loop
FIX: Using quoted aliases to preserve camelCase for frontend compatibility
 * GET /transactions/all
 */
export function useTransactionsAll(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['transactions-all', params],
    queryFn: () => api.get('/transactions/all', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - transactions/details
 * POST /transactions/details
 */
export function useCreateTransactionsDetails(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/transactions/details', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['transactions-details'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - transactions/lead_source_list
 * GET /transactions/lead_source_list
 */
export function useTransactionsLead_source_list(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['transactions-lead_source_list', params],
    queryFn: () => api.get('/transactions/lead_source_list', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - transactions/lead_source
 * POST /transactions/lead_source
 */
export function useCreateTransactionsLead_source(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/transactions/lead_source', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['transactions-lead_source'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - transactions/lead_type
 * POST /transactions/lead_type
 */
export function useCreateTransactionsLead_type(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/transactions/lead_type', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['transactions-lead_type'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - transactions/manual_entry
 * POST /transactions/manual_entry
 */
export function useCreateTransactionsManual_entry(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/transactions/manual_entry', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['transactions-manual_entry'] })
    },
    ...options,
  })
}

/**
 * OPTIMIZED transactions/metrics - uses db.direct_query for true SQL aggregation
 * GET /transactions/metrics
 */
export function useTransactionsMetrics(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['transactions-metrics', params],
    queryFn: () => api.get('/transactions/metrics', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - transactions/participants
 * GET /transactions/participants
 */
export function useTransactionsParticipants(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['transactions-participants', params],
    queryFn: () => api.get('/transactions/participants', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - transactions/update_effective_team
 * PATCH /transactions/update_effective_team
 */
export function useTransactionsUpdate_effective_team(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.patch('/transactions/update_effective_team', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['transactions-update_effective_team'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - update_api_key
 * POST /update_api_key
 */
export function useCreateUpdate_api_key(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/update_api_key', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['update_api_key'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - user/password
 * POST /user/password
 */
export function useCreateUserPassword(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/user/password', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['user-password'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - user_dashboard_configuration/batch
 * PATCH /user_dashboard_configuration/batch
 */
export function useUser_dashboard_configurationBatch(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.patch('/user_dashboard_configuration/batch', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['user_dashboard_configuration-batch'] })
    },
    ...options,
  })
}

/**
 * Delete a dashboard configuration (widget)
 * DELETE /user_dashboard_configuration/{id}
 */
export function useDeleteUser_dashboard_configuration(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.delete('/user_dashboard_configuration/{id}', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['user_dashboard_configuration-{id}'] })
    },
    ...options,
  })
}

/**
 * Update a dashboard widget configuration
 * PATCH /user_dashboard_configuration/{id}
 */
export function useUser_dashboard_configuration(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.patch('/user_dashboard_configuration/{id}', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['user_dashboard_configuration-{id}'] })
    },
    ...options,
  })
}

/**
 * Get user's dashboard configuration (favorites) with chart catalog data
 * GET /user_dashboard_configuration
 */
export function useUser_dashboard_configurationGet(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['user_dashboard_configuration', params],
    queryFn: () => api.get('/user_dashboard_configuration', { params }),
    ...options,
  })
}

/**
 * Add a widget to user's dashboard configuration
 * POST /user_dashboard_configuration
 */
export function useCreateUser_dashboard_configuration(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/user_dashboard_configuration', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['user_dashboard_configuration'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - user_dashboard_sections/reorder
 * POST /user_dashboard_sections/reorder
 */
export function useCreateUser_dashboard_sectionsReorder(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/user_dashboard_sections/reorder', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['user_dashboard_sections-reorder'] })
    },
    ...options,
  })
}

/**
 * Delete a dashboard section
 * DELETE /user_dashboard_sections/{id}
 */
export function useDeleteUser_dashboard_sections(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.delete('/user_dashboard_sections/{id}', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['user_dashboard_sections-{id}'] })
    },
    ...options,
  })
}

/**
 * Update a dashboard section
 * PATCH /user_dashboard_sections/{id}
 */
export function useUser_dashboard_sections(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.patch('/user_dashboard_sections/{id}', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['user_dashboard_sections-{id}'] })
    },
    ...options,
  })
}

/**
 * Get user dashboard sections
 * GET /user_dashboard_sections
 */
export function useUser_dashboard_sectionsGet(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['user_dashboard_sections', params],
    queryFn: () => api.get('/user_dashboard_sections', { params }),
    ...options,
  })
}

/**
 * Create a new dashboard section
 * POST /user_dashboard_sections
 */
export function useCreateUser_dashboard_sections(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/user_dashboard_sections', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['user_dashboard_sections'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - website/contact
 * POST /website/contact
 */
export function useCreateWebsiteContact(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/website/contact', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['website-contact'] })
    },
    ...options,
  })
}

/**
 * Fixed: website/note DELETE
 * DELETE /website/note
 */
export function useDeleteWebsiteNote(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.delete('/website/note', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['website-note'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - website/note
 * GET /website/note
 */
export function useWebsiteNote(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['website-note', params],
    queryFn: () => api.get('/website/note', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - website/note
 * POST /website/note
 */
export function useCreateWebsiteNote(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/website/note', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['website-note'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - website/notification_categories
 * GET /website/notification_categories
 */
export function useWebsiteNotification_categories(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['website-notification_categories', params],
    queryFn: () => api.get('/website/notification_categories', { params }),
    ...options,
  })
}

/**
 * Endpoint created via MCP - website/notifications/admins
 * POST /website/notifications/admins
 */
export function useCreateWebsiteNotificationsAdmins(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/website/notifications/admins', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['website-notifications-admins'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - website/notifications/daily
 * POST /website/notifications/daily
 */
export function useCreateWebsiteNotificationsDaily(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/website/notifications/daily', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['website-notifications-daily'] })
    },
    ...options,
  })
}

/**
 * Fixed: website/notifications/mark-read POST
 * POST /website/notifications/mark-read
 */
export function useCreateWebsiteNotificationsMarkRead(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/website/notifications/mark-read', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['website-notifications-mark-read'] })
    },
    ...options,
  })
}

/**
 * Fixed: website/notifications/mark_all_read POST
 * POST /website/notifications/mark_all_read
 */
export function useCreateWebsiteNotificationsMark_all_read(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/website/notifications/mark_all_read', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['website-notifications-mark_all_read'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - website/notifications/read
 * POST /website/notifications/read
 */
export function useCreateWebsiteNotificationsRead(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/website/notifications/read', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['website-notifications-read'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - website/notifications/weekly
 * POST /website/notifications/weekly
 */
export function useCreateWebsiteNotificationsWeekly(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/website/notifications/weekly', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['website-notifications-weekly'] })
    },
    ...options,
  })
}

/**
 * Fixed: website/notifications/{notification_id} DELETE
 * DELETE /website/notifications/{notification_id}
 */
export function useDeleteWebsiteNotifications(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.delete('/website/notifications/{notification_id}', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['website-notifications-{notification_id}'] })
    },
    ...options,
  })
}

/**
 * Get count of unread notifications for authenticated user
 * GET /website/notifications_count
 */
export function useWebsiteNotifications_count(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['website-notifications_count', params],
    queryFn: () => api.get('/website/notifications_count', { params }),
    ...options,
  })
}

/**
 * Fixed: website/notifications GET - using $auth.id instead of $authToken
 * GET /website/notifications
 */
export function useWebsiteNotifications(
  params?: Record<string, any>,
  options?: Omit<UseQueryOptions<any>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['website-notifications', params],
    queryFn: () => api.get('/website/notifications', { params }),
    ...options,
  })
}

/**
 * Fixed: website/raffle - using waitlist table
 * POST /website/raffle
 */
export function useCreateWebsiteRaffle(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/website/raffle', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['website-raffle'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - website/reset_admin_account
 * POST /website/reset_admin_account
 */
export function useCreateWebsiteReset_admin_account(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/website/reset_admin_account', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['website-reset_admin_account'] })
    },
    ...options,
  })
}

/**
 * Endpoint created via MCP - website/switch_view
 * POST /website/switch_view
 */
export function useCreateWebsiteSwitch_view(
  options?: UseMutationOptions<any, Error, any>
) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: any) => api.post('/website/switch_view', data),
    onSuccess: () => {
      // Invalidate related queries
      queryClient.invalidateQueries({ queryKey: ['website-switch_view'] })
    },
    ...options,
  })
}
